### ISSUE TITLE
Will not work with FastBoot

### ISSUE THREAD

**Issue by mminkoff** [dollarshaveclub/ember-router-scroll#85] opened 2018-01-29 22:26 UTC
pull request on the way!

**Comment by rwwagner90** [comment] 2018-02-07 04:07
@mminkoff when you say it does not work with fastboot, you mean if you run only in fastboot? It doesn't seem to cause any errors for me, but I was doing fastboot for initial boot and letting the browser take over.

Do you have a reproducible case?

**Comment by ryanto** [comment] 2018-02-10 03:55
Looks like this is causing a failure in fastboot: https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/services/router-scroll.js#L28-L29

**Comment by ryanto** [comment] 2018-02-11 21:03
Fixed in https://github.com/dollarshaveclub/ember-router-scroll/pull/92

**Comment by rwwagner90** [comment] 2018-02-11 23:31
Thanks @ryanto!

**Closed by rwwagner90** 2018-02-11 23:31 UTC
